apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: image-deployment
  template:
    metadata:
      labels:
        app: image-deployment
    spec:
      containers:
      - name: image-deployment
        image: mathieuvcnt/exerciceargocd:latestimage
        ports:
        - containerPort: 80
