name: Build and Test with Matrix

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env: 
      DOCKER_REGISTRY: mathieuvcnt/exerciceargocd 
    strategy:
      matrix:
        node-version: [12, 14, 16]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker image
      run: docker tag $DOCKER_REGISTRY:latest $DOCKER_REGISTRY:latest

    - name: Push Docker image to Docker Hub
      run: docker push $DOCKER_REGISTRY:latest

    - name: Clean up
      run: npm ci && npm run clean && npm cache clean --force

    - name: Run tests
      run: echo "Test réussi"
