name: Build and Test with Matrix

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env: 
      DOCKER_REGISTRY: mathieuvcnt/exerciceargocd 
    strategy:
      matrix:
        node-version: [16]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag Docker image
      run: |
        docker build -t $DOCKER_REGISTRY:latestimage .
        docker tag $DOCKER_REGISTRY:latestimage $DOCKER_REGISTRY:latestimage


    - name: Push Docker image to Docker Hub
      run: docker push $DOCKER_REGISTRY:latestimage

